INSERT INTO blog_posts (title, slug, excerpt, content, meta_title, meta_description, tags, category, cover_image, published, published_at, author_name) VALUES

('Cómo dar contención emocional en momentos de pérdida',
'contencion-emocional-momentos-de-perdida',
'Aprenda técnicas de contención emocional para acompañar a quienes atraviesan el duelo. Guía profesional de Funeraria Santa Margarita.',
E'La pérdida de un ser querido es uno de los momentos más difíciles que puede enfrentar una persona. En **Funeraria Santa Margarita**, entendemos que el acompañamiento emocional es tan importante como los servicios funerarios mismos.\n\n## ¿Qué es la contención emocional?\n\nLa contención emocional es el acto de brindar un espacio seguro donde la persona en duelo pueda expresar sus emociones sin juicio. No se trata de buscar palabras perfectas, sino de **estar presente** con empatía y respeto.\n\n## Técnicas fundamentales de contención\n\n### Escucha activa y empática\n\n- Mantenga contacto visual suave y respetuoso\n- No interrumpa ni intente completar frases\n- Valide las emociones sin minimizarlas\n- Use frases como \"entiendo que esto es muy difícil para usted\"\n\n### El poder del silencio acompañado\n\nA veces, las palabras sobran. Sentarse junto a alguien en silencio, tomándole la mano, puede ser más reconfortante que cualquier discurso.\n\n### Evite frases que no ayudan\n\n- **No diga**: \"Fue la voluntad de Dios\" o \"Al menos ya no sufre\"\n- **Sí diga**: \"Estoy aquí para lo que necesite\" o \"Su dolor es completamente válido\"\n\n---\n\n**¿Necesita apoyo profesional durante este momento difícil?** En Funeraria Santa Margarita ofrecemos acompañamiento integral 24/7. [Contáctenos ahora →](/contacto) o llame al **+56 9 6433 3760**.\n\n---\n\n## Cuándo buscar ayuda profesional\n\nSi el duelo se prolonga más de 6 meses con la misma intensidad, o si la persona muestra señales de depresión severa, es importante derivar a un profesional de salud mental.\n\n## El rol de la funeraria en la contención\n\nEn **Funeraria Santa Margarita**, nuestro equipo está capacitado para brindar contención desde el primer contacto. Sabemos que cada familia tiene necesidades únicas y nos adaptamos con sensibilidad a cada situación.\n\n## Preguntas Frecuentes\n\n### ¿Es normal sentir culpa después de una pérdida?\nSí, la culpa es una emoción frecuente en el duelo. Es importante reconocerla y trabajarla, idealmente con apoyo profesional.\n\n### ¿Cuánto tiempo dura el duelo?\nNo existe un plazo definido. Cada persona procesa la pérdida a su propio ritmo. Lo importante es no aislarse y buscar apoyo cuando sea necesario.',
'Contención emocional en duelo: Guía profesional',
'Técnicas de contención emocional para acompañar a personas en duelo. Guía de Funeraria Santa Margarita con apoyo 24/7.',
ARRAY['contención emocional', 'duelo', 'apoyo psicológico', 'acompañamiento'],
'Contención Emocional',
'/assets/images/blog/contencion-emocional.jpg',
true,
(NOW() - INTERVAL '2 days')::timestamptz,
'Funeraria Santa Margarita'),

('Primeras horas tras la pérdida: Cómo manejar el shock emocional',
'primeras-horas-shock-emocional-perdida',
'Guía para enfrentar el shock emocional en las primeras horas después de una pérdida. Orientación empática de Funeraria Santa Margarita.',
E'Las primeras horas después de recibir la noticia de un fallecimiento son las más difíciles. El **shock emocional** puede manifestarse de formas muy distintas: llanto, negación, parálisis o incluso una aparente calma.\n\n## Reacciones normales en las primeras horas\n\n### Fase de negación\n\nEs completamente natural que el cerebro necesite tiempo para procesar la realidad. Frases como \"esto no puede estar pasando\" son parte del proceso.\n\n### Síntomas físicos del shock\n\n- Temblores y escalofríos\n- Sensación de irrealidad\n- Dificultad para respirar\n- Mareos o náuseas\n- Insomnio\n\n## Qué hacer en las primeras horas\n\n### Prioridad 1: Acompañamiento\n\nNo deje sola a la persona en shock. La presencia física de alguien cercano es fundamental para la estabilidad emocional.\n\n### Prioridad 2: Hidratación y descanso\n\nAunque la persona no tenga apetito, ofrézcale agua y un espacio tranquilo para descansar.\n\n### Prioridad 3: Contactar ayuda profesional\n\nComuníquese con una funeraria de confianza que pueda encargarse de los trámites mientras la familia procesa la pérdida.\n\n---\n\n**En Funeraria Santa Margarita nos encargamos de todo.** Desde la inscripción en el Registro Civil hasta la coordinación completa del servicio. [Conozca nuestros planes →](/planes) desde **$1.290.000** con cobertura integral.\n\n---\n\n## El rol del acompañante\n\nSi usted es quien acompaña, recuerde:\n\n- **No presione** a la persona para que hable o coma\n- **Tome decisiones prácticas** por ella cuando sea necesario\n- **Coordine** con la funeraria para aliviar la carga\n- **Cuídese también**: el acompañante también necesita espacio para procesar\n\n## Preguntas Frecuentes\n\n### ¿Es normal no poder llorar?\nSí. El shock puede bloquear temporalmente las emociones. Las lágrimas pueden llegar días o semanas después.\n\n### ¿Debo llevar a los niños al funeral?\nDepende de la edad y madurez del niño. Lo recomendable es explicarles la situación con honestidad y dejarles decidir si desean asistir.',
'Shock emocional tras pérdida: Qué hacer',
'Guía para manejar el shock emocional en las primeras horas tras una pérdida. Orientación profesional 24/7.',
ARRAY['shock emocional', 'primeras horas', 'duelo agudo', 'contención'],
'Contención Emocional',
'/assets/images/blog/contencion-emocional.jpg',
true,
(NOW() - INTERVAL '5 days')::timestamptz,
'Funeraria Santa Margarita'),

('Duelo y salud mental: Cuándo buscar ayuda profesional',
'duelo-salud-mental-cuando-buscar-ayuda',
'Identifique las señales de un duelo complicado y sepa cuándo es necesario buscar apoyo de salud mental.',
E'El duelo es un proceso natural, pero en algunos casos puede derivar en complicaciones que afectan seriamente la **salud mental**. Reconocer las señales a tiempo es fundamental.\n\n## Duelo normal vs. duelo complicado\n\n### Duelo normal\n\n- Tristeza intensa que disminuye gradualmente\n- Capacidad de retomar actividades cotidianas\n- Momentos de alegría entre el dolor\n- Aceptación progresiva de la realidad\n\n### Duelo complicado (prolongado)\n\n- Dolor intenso que no disminuye después de 12 meses\n- Incapacidad de aceptar la pérdida\n- Aislamiento social progresivo\n- Pensamientos recurrentes sobre la muerte\n\n## Señales de alerta en salud mental\n\n### Depresión post-duelo\n\nSi observa estos síntomas por más de 2 semanas, consulte a un profesional:\n\n- Pérdida total de interés en actividades\n- Insomnio o hipersomnia persistente\n- Cambios drásticos en el peso\n- Ideas de autolesión\n\n### Ansiedad severa\n\n- Ataques de pánico frecuentes\n- Miedo irracional a perder a otros seres queridos\n- Hipervigilancia constante\n\n---\n\n**¿Tiene preguntas sobre cómo enfrentar el duelo?** Visite nuestra sección de [Preguntas Frecuentes →](/preguntas-frecuentes) donde abordamos las dudas más comunes con empatía y profesionalismo.\n\n---\n\n## Recursos de apoyo en Chile\n\n- **Salud Responde**: 600 360 7777 (24 horas)\n- **Línea Libre**: 1515 (apoyo emocional gratuito)\n\n## Preguntas Frecuentes\n\n### ¿Es necesario ir al psicólogo después de un fallecimiento?\nNo siempre, pero es recomendable cuando el duelo interfiere significativamente con la vida cotidiana por un período prolongado.\n\n### ¿Los niños necesitan terapia de duelo?\nDepende de cada caso. Si nota cambios significativos en el comportamiento o rendimiento escolar, es aconsejable una evaluación profesional.',
'Duelo y salud mental: Señales para buscar ayuda',
'Identifique señales de duelo complicado y sepa cuándo buscar ayuda profesional de salud mental.',
ARRAY['salud mental', 'duelo complicado', 'depresión', 'ansiedad'],
'Salud Mental',
'/assets/images/blog/salud-mental.jpg',
true,
(NOW() - INTERVAL '3 days')::timestamptz,
'Funeraria Santa Margarita'),

('El duelo en adultos mayores: Cuidados especiales',
'duelo-adultos-mayores-salud-mental',
'Los adultos mayores enfrentan el duelo de forma particular. Conozca cómo cuidar su salud mental y ofrecerles apoyo adecuado.',
E'Los adultos mayores constituyen uno de los grupos más vulnerables frente a la pérdida. La acumulación de duelos a lo largo de la vida hace que este proceso sea especialmente delicado.\n\n## Particularidades del duelo en la tercera edad\n\n### Duelos acumulados\n\nA diferencia de personas más jóvenes, los adultos mayores suelen enfrentar **múltiples pérdidas** cercanas en un período corto: pareja, hermanos, amigos.\n\n### Manifestaciones somáticas\n\nEn la tercera edad, el duelo tiende a expresarse más a través del cuerpo:\n\n- Dolores musculares y articulares\n- Pérdida significativa de apetito\n- Deterioro cognitivo temporal\n- Agravamiento de enfermedades crónicas\n\n## Cómo apoyar a un adulto mayor en duelo\n\n### Mantener rutinas\n\nLas rutinas proporcionan estructura y previsibilidad. Ayude a mantener horarios de comida, paseos y actividades.\n\n### Compañía sin invasión\n\nVisite regularmente pero respete los tiempos de soledad que la persona necesite.\n\n### Vigilar señales de alarma\n\n- Descuido severo de la higiene personal\n- Confusión mental persistente\n- Expresiones de querer \"irse\" con la persona fallecida\n\n---\n\n**En Funeraria Santa Margarita entendemos cada etapa de la vida.** Nuestros planes funerarios están diseñados para dar tranquilidad a toda la familia. [Solicite una cotización personalizada →](/contacto) o conozca nuestro [Plan Raulí desde $3.990.000 →](/planes).\n\n---\n\n## El valor de la previsión para adultos mayores\n\nPlanificar con anticipación no es un acto morboso, sino de **amor y responsabilidad**. Cuando un adulto mayor tiene su plan funerario organizado, libera a su familia de la carga de tomar decisiones difíciles.\n\n## Preguntas Frecuentes\n\n### ¿Es normal que un adulto mayor se deje estar tras perder a su pareja?\nLa apatía es una reacción frecuente, pero si se prolonga más de un mes, es importante consultar al médico.\n\n### ¿Cómo hablar de la muerte con un adulto mayor?\nCon naturalidad y respeto. Muchos adultos mayores agradecen poder hablar abiertamente sobre este tema.',
'Duelo en adultos mayores: Cuidados de salud mental',
'Guía sobre el duelo en adultos mayores, señales de alerta y cuidados especiales de salud mental.',
ARRAY['adultos mayores', 'salud mental', 'duelo', 'tercera edad'],
'Salud Mental',
'/assets/images/blog/salud-mental.jpg',
true,
(NOW() - INTERVAL '8 days')::timestamptz,
'Funeraria Santa Margarita'),

('Ansiedad por la muerte: Cómo manejar la tanatofobia',
'ansiedad-muerte-miedo-perder-seres-queridos',
'La tanatofobia o ansiedad por la muerte es más común de lo que parece. Aprenda a manejarla con herramientas prácticas.',
E'La **ansiedad por la muerte**, también llamada tanatofobia, es un temor profundo y persistente a la muerte propia o de seres queridos.\n\n## ¿Qué es la tanatofobia?\n\nEs un miedo intenso y desproporcionado a la muerte que puede manifestarse como:\n\n- Pensamientos obsesivos sobre la muerte\n- Evitación de hospitales, funerales o cementerios\n- Ataques de pánico al pensar en la mortalidad\n- Hipervigilancia sobre la salud propia y de seres queridos\n\n## Herramientas para manejar la ansiedad\n\n### Aceptación como camino\n\nLa filosofía estoica nos enseña que aceptar la finitud de la vida no es resignación, sino **sabiduría**.\n\n### Técnicas de regulación emocional\n\n- **Respiración diafragmática**: 4 segundos inhalar, 7 segundos sostener, 8 segundos exhalar\n- **Grounding sensorial**: identificar 5 cosas que ve, 4 que toca, 3 que escucha\n- **Journaling**: escribir los miedos para externalizarlos\n\n### Terapia cognitivo-conductual\n\nEs el tratamiento más eficaz para la tanatofobia.\n\n---\n\n**La previsión funeraria reduce significativamente la ansiedad.** Saber que todo está organizado brinda paz mental. [Conozca nuestros planes de previsión →](/planes) desde **$1.290.000**.\n\n---\n\n## Cuándo la previsión ayuda a la ansiedad\n\nMuchas personas que sufren ansiedad por la muerte encuentran alivio al **planificar con anticipación**. Al tener un plan funerario contratado, el miedo a \"dejar problemas\" a la familia disminuye considerablemente.\n\n## Preguntas Frecuentes\n\n### ¿Es normal tener miedo a la muerte?\nSí, es una emoción humana universal. Solo se considera problemática cuando interfiere con la calidad de vida.\n\n### ¿La previsión funeraria puede ayudar con la ansiedad?\nSí. Muchos clientes reportan mayor tranquilidad después de organizar su plan funerario.',
'Ansiedad por la muerte: Cómo manejar la tanatofobia',
'Aprenda a manejar la ansiedad por la muerte con técnicas prácticas. La previsión funeraria como herramienta de paz mental.',
ARRAY['tanatofobia', 'ansiedad', 'salud mental', 'previsión'],
'Salud Mental',
'/assets/images/blog/salud-mental.jpg',
true,
(NOW() - INTERVAL '12 days')::timestamptz,
'Funeraria Santa Margarita'),

('Cómo explicar la muerte a los niños: Guía para familias',
'como-explicar-muerte-a-ninos-guia-familias',
'Orientación profesional para hablar de la muerte con niños según su edad. Consejos empáticos para familias en duelo.',
E'Hablar de la muerte con los niños es uno de los desafíos más difíciles para las familias. Los expertos coinciden en que la **honestidad adaptada a la edad** es siempre mejor que el silencio.\n\n## Según la edad del niño\n\n### De 2 a 5 años\n\nLos niños pequeños no comprenden la irreversibilidad de la muerte.\n\n- Use lenguaje simple y concreto\n- **Evite**: \"Se fue a dormir\" o \"Lo perdimos\"\n- **Diga**: \"El cuerpo del abuelito dejó de funcionar y ya no puede volver\"\n- Permita que hagan preguntas, aunque se repitan\n\n### De 6 a 9 años\n\nComienzan a entender que la muerte es permanente, pero pueden sentirse culpables.\n\n- Aclare que nada de lo que hicieron causó la muerte\n- Permita la participación en rituales si lo desean\n- Mantenga sus rutinas escolares y sociales\n\n### De 10 a 12 años\n\nComprenden plenamente el concepto de muerte.\n\n- Responda preguntas con honestidad\n- Valide sus emociones sin juzgar\n- Ofrezca espacio para expresarse por escrito o arte\n\n---\n\n**En Funeraria Santa Margarita creamos ceremonias que incluyen a toda la familia.** Nuestras [ceremonias personalizadas →](/contacto) permiten adaptar el ritual para que los niños también puedan participar. Llame al **+56 9 6433 3760**.\n\n---\n\n## ¿Deben asistir los niños al funeral?\n\nConsidere:\n\n- **A favor**: participar les ayuda a comprender la realidad y a despedirse\n- **En contra**: si el niño muestra mucho miedo o ansiedad, no lo fuerce\n- **Alternativa**: crear un ritual privado en casa\n\n## Señales de duelo complicado en niños\n\n- Regresión (volver a mojar la cama, chuparse el dedo)\n- Agresividad inusual\n- Bajo rendimiento escolar persistente\n- Aislamiento de amigos\n\n## Preguntas Frecuentes\n\n### ¿A qué edad se puede hablar de la muerte con un niño?\nDesde los 2-3 años se puede introducir el concepto gradualmente, usando ejemplos de la naturaleza.\n\n### ¿Es bueno que los niños vean llorar a sus padres?\nSí. Ver a los adultos expresar emociones les enseña que llorar es normal y saludable.',
'Cómo explicar la muerte a niños: Guía por edades',
'Guía para hablar de la muerte con niños según su edad. Consejos empáticos para familias en duelo.',
ARRAY['niños', 'duelo infantil', 'apoyo familiar', 'explicar muerte'],
'Apoyo Familiar',
'/assets/images/blog/apoyo-familiar.jpg',
true,
(NOW() - INTERVAL '4 days')::timestamptz,
'Funeraria Santa Margarita'),

('Roles familiares en el duelo: Cómo organizarse tras la pérdida',
'roles-familiares-duelo-organizarse-tras-perdida',
'Descubra cómo distribuir responsabilidades en la familia tras un fallecimiento para evitar sobrecarga y conflictos.',
E'Cuando una familia pierde a un ser querido, las dinámicas internas pueden alterarse profundamente. Es común que una sola persona asuma toda la carga.\n\n## Los roles que surgen en el duelo\n\n### El organizador\n\nEs quien asume la coordinación con la funeraria, los trámites legales y la logística del servicio.\n\n### El cuidador emocional\n\nQuien contiene a los demás miembros de la familia, a menudo descuidando su propio duelo.\n\n### El invisible\n\nMiembros que se aíslan o cuyo dolor pasa desapercibido (yernos, nueras, nietos adolescentes).\n\n## Cómo distribuir responsabilidades\n\n### Lista de tareas por categorías\n\n**Trámites legales**:\n- Certificado de defunción\n- Inscripción en Registro Civil\n- Trámites de herencia y cuota mortuoria\n\n**Logística del servicio**:\n- Coordinar con la funeraria\n- Avisar a familiares y amigos\n- Organizar traslados\n\n---\n\n**Con Funeraria Santa Margarita, el organizador no está solo.** Nos encargamos de todos los trámites. Desde nuestro [Plan Margarita a $1.290.000 →](/planes) hasta el [Plan Castaño a $3.990.000 →](/planes), cada detalle queda en manos profesionales.\n\n---\n\n## Evitar conflictos familiares\n\n### Comunicación clara\n\nEstablezcan un grupo familiar donde se compartan las decisiones y avances.\n\n### Respetar los tiempos de cada uno\n\nNo todos procesan el duelo al mismo ritmo. Evite juzgar.\n\n## Preguntas Frecuentes\n\n### ¿Qué pasa si la familia no se pone de acuerdo en el tipo de servicio?\nEn Funeraria Santa Margarita ofrecemos orientación para ayudar a las familias a encontrar un consenso que honre los deseos del fallecido.\n\n### ¿Puedo delegar todos los trámites a la funeraria?\nSí. Nuestros planes incluyen la gestión completa de trámites ante el Registro Civil.',
'Roles familiares en el duelo: Organización y apoyo',
'Cómo distribuir responsabilidades familiares tras un fallecimiento. Evite sobrecarga y conflictos.',
ARRAY['familia', 'roles', 'organización', 'duelo familiar'],
'Apoyo Familiar',
'/assets/images/blog/apoyo-familiar.jpg',
true,
(NOW() - INTERVAL '9 days')::timestamptz,
'Funeraria Santa Margarita'),

('Duelo en pareja: Cómo apoyarse mutuamente tras una pérdida',
'duelo-en-pareja-perdida-de-un-hijo',
'La pérdida de un hijo es devastadora para la pareja. Conozca estrategias para sobrellevar el duelo juntos.',
E'La pérdida de un hijo es considerada una de las experiencias más devastadoras que puede enfrentar un ser humano. Para la pareja, este dolor compartido puede ser un camino hacia la unión o hacia la fractura.\n\n## El impacto en la relación\n\n### Diferencias en el duelo\n\nEs fundamental entender que hombres y mujeres suelen procesar el duelo de forma distinta:\n\n- **Duelo intuitivo**: expresión abierta de emociones (más frecuente en mujeres)\n- **Duelo instrumental**: canalización a través de la acción (más frecuente en hombres)\n\nNinguna forma es mejor que la otra.\n\n## Estrategias para la pareja\n\n### Comunicación sin expectativas\n\n- Compartan lo que sienten sin esperar que el otro sienta lo mismo\n- Usen la fórmula: \"Yo siento...\" en vez de \"Tú no estás...\"\n- Establezcan momentos diarios para hablar\n\n### Rituales compartidos\n\n- Visitar juntos el memorial o cementerio\n- Crear un espacio de memoria en el hogar\n- Escribir cartas al hijo fallecido\n\n### Terapia de pareja especializada\n\nUn terapeuta especializado en duelo puede ser fundamental.\n\n---\n\n**Nuestros memoriales digitales permiten honrar la memoria para siempre.** En Funeraria Santa Margarita creamos [memoriales personalizados →](/memoriales) donde familiares y amigos pueden dejar condolencias y homenajes.\n\n---\n\n## Cuándo buscar ayuda urgente\n\n- Si uno o ambos miembros expresan ideación suicida\n- Si hay aumento en consumo de alcohol o sustancias\n- Si la comunicación se ha roto completamente\n\n## Preguntas Frecuentes\n\n### ¿Es normal que la pareja tenga conflictos después de una pérdida?\nSí. Las diferencias en el proceso de duelo pueden generar malentendidos. La terapia de pareja es altamente recomendable.\n\n### ¿Cómo manejar las fechas especiales?\nAcuerden juntos cómo desean vivirlas. Lo importante es que ambos se sientan cómodos.',
'Duelo en pareja: Apoyarse mutuamente tras la pérdida',
'Estrategias para parejas que enfrentan una pérdida. Cómo fortalecer el vínculo en el duelo compartido.',
ARRAY['duelo en pareja', 'pérdida', 'apoyo familiar', 'terapia de pareja'],
'Apoyo Familiar',
'/assets/images/blog/apoyo-familiar.jpg',
true,
(NOW() - INTERVAL '15 days')::timestamptz,
'Funeraria Santa Margarita'),

('Comparativa de planes funerarios en Chile 2025',
'comparativa-planes-funerarios-chile-2025',
'Compare los planes funerarios disponibles en Chile. Análisis detallado de servicios, precios y coberturas.',
E'Elegir un plan funerario es una decisión importante que merece **información clara y transparente**.\n\n## ¿Qué debe incluir un buen plan funerario?\n\n- **Inscripción en el Registro Civil**: trámite obligatorio\n- **Vehículo mortuorio**: traslado digno y profesional\n- **Urna o ataúd**: de calidad acorde al plan\n- **Servicio de velatorio**: espacio adecuado\n- **Arreglos florales**: decoración digna\n\n## Planes de Funeraria Santa Margarita\n\n### Plan Margarita — $1.290.000\n\n- Inscripción Registro Civil\n- Vehículo mortuorio\n- Servicio profesional completo\n\n### Plan Azucena — $1.390.000\n\n- Arreglo floral\n- 50 tarjetas de agradecimiento\n\n### Plan Acacia — $1.990.000\n\n- Urna Modelo Acacia\n- Arreglo floral premium\n\n### Plan Orquídea — $1.990.000\n\n- Urna Modelo Orquídea\n- Arreglo floral selecto\n\n### Plan Jazmín — $2.790.000\n\n- Urna Modelo Jazmín\n- Servicio Premium personalizado\n\n### Plan Castaño — $3.990.000\n\n- 2 arreglos florales\n- Cafetería para 50 personas\n\n### Plan Raulí — $3.990.000\n\n- Certificación médica incluida\n- Aviso de prensa\n\n---\n\n**¿Necesita ayuda para elegir?** Nuestros asesores le guiarán sin presión. [Solicite una cotización →](/contacto) o llame al **+56 9 6433 3760** (24/7).\n\n---\n\n## Factores a considerar\n\n### Presupuesto familiar\n\nEvalúe con calma cuánto puede destinar. Recuerde la **cuota mortuoria** que puede ayudar.\n\n### Tipo de ceremonia deseada\n\n¿Prefiere una ceremonia íntima o con amplia asistencia?\n\n### Previsión vs. necesidad inmediata\n\nContratar un plan de previsión suele tener **mejores condiciones**.\n\n## Preguntas Frecuentes\n\n### ¿Se puede pagar un plan funerario en cuotas?\nSí. Ofrecemos opciones de pago flexibles. Contáctenos para conocer las alternativas.\n\n### ¿Qué pasa si necesito un servicio más completo?\nSiempre es posible agregar servicios adicionales al plan base.',
'Planes funerarios Chile 2025: Comparativa de precios',
'Compare planes funerarios en Chile desde $1.290.000. Servicios, precios y coberturas.',
ARRAY['planes funerarios', 'precios', 'comparativa', 'Chile 2025'],
'Previsión',
'/assets/images/blog/prevision.jpg',
true,
(NOW() - INTERVAL '1 day')::timestamptz,
'Funeraria Santa Margarita'),

('Seguro funerario vs. plan de previsión: Diferencias clave',
'seguro-funerario-vs-plan-prevision-diferencias',
'Conozca las diferencias entre un seguro funerario y un plan de previsión. Ventajas, desventajas y cuál conviene más.',
E'Muchas familias confunden los **seguros funerarios** con los **planes de previsión**. Aunque ambos buscan cubrir gastos funerarios, funcionan de manera muy distinta.\n\n## ¿Qué es un seguro funerario?\n\nEs un producto financiero que paga una indemnización en dinero al momento del fallecimiento. La familia recibe el dinero y debe contratar la funeraria por su cuenta.\n\n### Ventajas del seguro\n\n- Primas mensuales bajas\n- Flexibilidad para elegir funeraria\n\n### Desventajas del seguro\n\n- **No garantiza el servicio**: la familia debe buscar y negociar\n- **Inflación**: el monto puede ser insuficiente\n- **Letra chica**: exclusiones y limitaciones\n\n## ¿Qué es un plan de previsión funeraria?\n\nEs un contrato directo con una funeraria que **garantiza el servicio completo** independiente de la inflación futura.\n\n### Ventajas de la previsión\n\n- **Precio congelado**: paga el valor de hoy\n- **Sin trámites en el momento**: la funeraria se encarga de todo\n- **Tranquilidad total**: la familia no debe tomar decisiones bajo presión\n- **Servicio garantizado**: incluye todos los elementos contratados\n\n---\n\n**En Funeraria Santa Margarita le ofrecemos previsión con precio congelado.** [Conozca nuestros planes →](/planes) o visite nuestras [Preguntas Frecuentes →](/preguntas-frecuentes).\n\n---\n\n## Nuestra recomendación\n\nSi lo que busca es **tranquilidad real** para su familia, un plan de previsión con una funeraria de confianza es siempre la mejor opción.\n\n## Preguntas Frecuentes\n\n### ¿Puedo tener ambos al mismo tiempo?\nSí. Algunas familias usan el seguro como complemento.\n\n### ¿Qué pasa si la funeraria cierra?\nEn Funeraria Santa Margarita respaldamos cada plan con garantías contractuales.',
'Seguro funerario vs plan previsión: Cuál elegir',
'Diferencias entre seguro funerario y plan de previsión en Chile. Ventajas, costos y cuál conviene más.',
ARRAY['seguro funerario', 'previsión', 'comparativa', 'planificación'],
'Previsión',
'/assets/images/blog/prevision.jpg',
true,
(NOW() - INTERVAL '10 days')::timestamptz,
'Funeraria Santa Margarita'),

('Traslado funerario en Chile: Requisitos y opciones',
'traslado-funerario-chile-requisitos-opciones',
'Todo sobre el traslado funerario en Chile: requisitos legales, opciones nacionales e internacionales.',
E'El **traslado funerario** es uno de los servicios más solicitados, especialmente cuando el fallecimiento ocurre en una ciudad distinta al lugar de residencia.\n\n## Tipos de traslado funerario\n\n### Traslado comunal/local\n\nDentro de la misma ciudad. Es el más sencillo y está incluido en la mayoría de los planes.\n\n### Traslado interregional\n\nEntre distintas regiones de Chile. Requiere documentación adicional.\n\n### Traslado internacional (repatriación)\n\nCuando el fallecimiento ocurre en el extranjero. Es el proceso más complejo.\n\n## Requisitos legales en Chile\n\n### Documentación obligatoria\n\n- **Certificado de defunción**\n- **Inscripción en el Registro Civil**\n- **Pase de tránsito**: autoriza el traslado\n- **Certificado sanitario**: emitido por SEREMI de Salud\n\n### Para traslados internacionales\n\n- Certificado de embalsamamiento\n- Legalización de documentos\n- Coordinación con aerolínea\n- Ataúd especial para transporte aéreo\n\n---\n\n**En Funeraria Santa Margarita gestionamos todo el proceso de traslado.** [Contacte a nuestro equipo 24/7 →](/contacto) o llame al **+56 9 6433 3760**.\n\n---\n\n## Costos estimados\n\n- **Traslado local**: incluido en el plan funerario\n- **Traslado interregional**: varía según distancia\n- **Repatriación**: consultar según país\n\n## Preguntas Frecuentes\n\n### ¿Puedo trasladar restos cremados?\nSí. El traslado de cenizas es más sencillo y económico.\n\n### ¿Cuánto demora un traslado interregional?\nGeneralmente entre 12 y 48 horas.',
'Traslado funerario Chile: Requisitos y opciones',
'Guía completa sobre traslado funerario en Chile: requisitos, tipos, costos y gestión profesional.',
ARRAY['traslado funerario', 'repatriación', 'servicios funerarios'],
'Servicios',
'/assets/images/blog/servicios.jpg',
true,
(NOW() - INTERVAL '6 days')::timestamptz,
'Funeraria Santa Margarita'),

('Velatorio y ceremonias: Opciones para una despedida digna',
'velatorio-ceremonias-opciones-despedida-digna',
'Conozca las opciones de velatorio y ceremonia disponibles en Chile. Desde servicios tradicionales hasta ceremonias personalizadas.',
E'El velatorio y la ceremonia fúnebre son momentos fundamentales para la despedida y el proceso de duelo.\n\n## Tipos de velatorio\n\n### Velatorio tradicional\n\nSe realiza en una sala velatoria durante 12 a 24 horas:\n\n- Sala con capacidad adecuada\n- Iluminación y ambientación solemne\n- Sillas y elementos de confort\n- Servicio de cafetería (según plan)\n\n### Velatorio en domicilio\n\nAlgunas familias prefieren velar en casa. Más íntimo y significativo.\n\n### Velatorio express\n\nDuración de 4-6 horas para situaciones que requieren agilidad.\n\n## Tipos de ceremonia\n\n### Ceremonia religiosa\n\nLa más tradicional en Chile. Puede ser católica, evangélica u otra confesión.\n\n### Ceremonia civil o laica\n\nPermite personalizar completamente el contenido con lecturas, música, videos y testimonios.\n\n### Ceremonia al aire libre\n\nCada vez más popular. Permite la despedida en un lugar significativo.\n\n---\n\n**Nuestros planes incluyen velatorio y ceremonia completa.** Desde el [Plan Margarita →](/planes) con servicio esencial hasta el [Plan Castaño →](/planes) con cafetería para 50 personas. [Solicite una cotización →](/contacto).\n\n---\n\n## Elementos para personalizar la ceremonia\n\n- **Música**: seleccione las canciones favoritas\n- **Fotografías**: montaje visual con momentos significativos\n- **Flores**: arreglos personalizados\n- **Lecturas**: poemas, textos o cartas de familiares\n\n## Preguntas Frecuentes\n\n### ¿Puedo llevar música propia al velatorio?\nSí. Facilitamos equipo de audio para reproducir la música que desee.\n\n### ¿Es obligatorio hacer velatorio antes del entierro?\nNo es legalmente obligatorio, pero es una tradición arraigada que ayuda en el proceso de duelo.',
'Velatorio y ceremonias funerarias en Chile',
'Opciones de velatorio y ceremonia en Chile. Servicios tradicionales y personalizados.',
ARRAY['velatorio', 'ceremonia funeraria', 'despedida', 'servicios funerarios'],
'Servicios',
'/assets/images/blog/servicios.jpg',
true,
(NOW() - INTERVAL '7 days')::timestamptz,
'Funeraria Santa Margarita'),

('Las 5 etapas del duelo: Comprenda su proceso de sanación',
'cinco-etapas-duelo-proceso-sanacion',
'Conozca las 5 etapas del duelo según Kübler-Ross y entienda que cada persona tiene su propio ritmo de sanación.',
E'El modelo de las **5 etapas del duelo** propuesto por Elisabeth Kübler-Ross sigue siendo una herramienta clave para comprender la pérdida.\n\n## Las 5 etapas\n\n### 1. Negación\n\n\"Esto no puede estar pasando\". La negación actúa como un **mecanismo de defensa** que protege del shock inicial.\n\n### 2. Ira\n\n\"¿Por qué a mí?\". La rabia puede dirigirse hacia médicos, hacia Dios, hacia uno mismo o hacia la persona fallecida. Es legítima y necesaria.\n\n### 3. Negociación\n\n\"Si pudiera volver el tiempo atrás...\". La mente busca formas de revertir lo irreversible.\n\n### 4. Depresión\n\n\"Ya nada tiene sentido\". No es enfermedad mental, sino una respuesta natural a la magnitud de la pérdida.\n\n### 5. Aceptación\n\n\"Puedo vivir con esto\". Aceptar no significa olvidar. Significa integrar la pérdida en la propia historia.\n\n---\n\n**Usted no está solo en este proceso.** En Funeraria Santa Margarita ofrecemos acompañamiento integral. [Conozca cómo podemos ayudarle →](/contacto) o visite nuestras [Preguntas Frecuentes →](/preguntas-frecuentes).\n\n---\n\n## Lo que las etapas NO son\n\n### No son lineales\n\nEs normal saltar entre etapas o experimentar varias al mismo tiempo.\n\n### No son obligatorias\n\nNo todas las personas pasan por las 5 etapas. Cada duelo es único.\n\n### No tienen plazo\n\nNo existe un tiempo \"correcto\" para cada etapa.\n\n## Preguntas Frecuentes\n\n### ¿Es malo no sentir las 5 etapas?\nNo. El modelo es una guía, no una regla.\n\n### ¿Puedo estar en dos etapas al mismo tiempo?\nSí. Es completamente normal sentir ira y tristeza simultáneamente.',
'Las 5 etapas del duelo: Guía de comprensión',
'Comprenda las 5 etapas del duelo de Kübler-Ross. Cada persona tiene su ritmo. Apoyo 24/7.',
ARRAY['etapas del duelo', 'Kübler-Ross', 'duelo', 'sanación'],
'Duelo',
'/assets/images/blog/duelo.jpg',
true,
(NOW() - INTERVAL '11 days')::timestamptz,
'Funeraria Santa Margarita'),

('Rituales de despedida que ayudan en el proceso de duelo',
'rituales-despedida-ayudan-proceso-duelo',
'Descubra rituales de despedida significativos que facilitan el duelo: ceremonias personalizadas y memoriales digitales.',
E'Los **rituales de despedida** cumplen una función psicológica fundamental: marcan un antes y un después, ayudando al cerebro a procesar la realidad.\n\n## ¿Por qué son importantes los rituales?\n\n### Función psicológica\n\nProporcionan **estructura** en un momento de caos emocional. Dan un marco temporal al dolor.\n\n### Función social\n\nReúnen a la comunidad alrededor de la familia en duelo, creando una red de apoyo.\n\n### Función espiritual\n\nConectan con algo más grande, ofreciendo consuelo y sentido.\n\n## Rituales tradicionales y modernos\n\n### Rituales tradicionales\n\n- **Velatorio**: acompañar al difunto durante la noche\n- **Misa de cuerpo presente**: ceremonia religiosa\n- **Novenario**: nueve días de oración\n- **Misa de mes y año**: recordación\n\n### Rituales modernos\n\n- **Ceremonia de vida**: centrada en celebrar la vida vivida\n- **Memorial digital**: espacio permanente en línea\n- **Plantación de un árbol**: símbolo de que la vida continúa\n- **Suelta de mariposas**: gesto visual de liberación\n\n---\n\n**Creamos memoriales digitales permanentes.** Visite nuestra sección de [Memoriales →](/memoriales) y descubra cómo preservar su legado. También puede conocer nuestras [ceremonias personalizadas →](/contacto).\n\n---\n\n## Cómo crear un ritual significativo\n\n### Paso 1: Identifique qué era importante para el difunto\n\n¿Amaba la naturaleza? ¿Era músico? Use estos elementos como base.\n\n### Paso 2: Involucre a la familia\n\nPida a cada miembro que aporte un elemento: una lectura, una canción, un recuerdo.\n\n### Paso 3: Defina un momento y lugar\n\nLos rituales pueden realizarse en cualquier momento que la familia considere apropiado.\n\n## Preguntas Frecuentes\n\n### ¿Puedo crear un ritual propio sin iglesia?\nSí. Las ceremonias civiles permiten total libertad para personalizar.\n\n### ¿Los memoriales digitales reemplazan al cementerio?\nNo los reemplazan, sino que los complementan con accesibilidad desde cualquier lugar.',
'Rituales de despedida: Guía para el proceso de duelo',
'Rituales de despedida que facilitan el duelo: ceremonias personalizadas y memoriales digitales.',
ARRAY['rituales funerarios', 'despedida', 'duelo', 'ceremonias', 'memoriales'],
'Duelo',
'/assets/images/blog/duelo.jpg',
true,
(NOW() - INTERVAL '14 days')::timestamptz,
'Funeraria Santa Margarita'),

('Herencia y sucesión en Chile: Guía de trámites legales',
'herencia-sucesion-chile-tramites-fallecimiento',
'Guía completa sobre herencia y sucesión en Chile. Plazos, documentos y pasos legales para la posesión efectiva.',
E'Tras el fallecimiento, además del dolor, la familia debe enfrentar **trámites legales** de herencia y sucesión.\n\n## ¿Qué es la posesión efectiva?\n\nEs el trámite legal que permite a los herederos disponer de los bienes del fallecido. Es requisito para:\n\n- Transferir propiedades inmuebles\n- Acceder a cuentas bancarias\n- Realizar trámites vehiculares\n- Cobrar seguros de vida\n\n## Pasos para tramitar\n\n### Paso 1: Obtener el certificado de defunción\n\nSolicitarlo en el **Registro Civil** o en línea.\n\n### Paso 2: Identificar el tipo\n\n- **Sin testamento (intestada)**: ante el Registro Civil\n- **Con testamento (testada)**: ante un tribunal civil\n\n### Paso 3: Reunir documentación\n\n- Certificado de defunción\n- Certificado de matrimonio (si aplica)\n- Certificados de nacimiento de herederos\n- Inventario de bienes\n- Certificados de dominio\n\n### Paso 4: Presentar la solicitud\n\nPara intestadas, el trámite puede hacerse en línea.\n\n### Paso 5: Publicación en el Diario Oficial\n\nSe publica e inscribe en el Conservador de Bienes Raíces.\n\n---\n\n**Mientras usted se encarga de los trámites legales, nosotros nos encargamos de todo lo demás.** [Conozca nuestros planes →](/planes) con gestión completa incluida.\n\n---\n\n## Plazos importantes\n\n- **Posesión efectiva**: sin plazo legal, pero hacerlo pronto es recomendable\n- **Impuesto a la herencia**: dentro de los 2 años\n- **Cuota mortuoria**: solicitar dentro de los primeros meses\n\n## Preguntas Frecuentes\n\n### ¿Puedo hacer la posesión efectiva sin abogado?\nPara casos intestados simples, sí. Para casos complejos es recomendable asesoría.\n\n### ¿Cuánto cuesta la posesión efectiva?\nEl trámite ante el Registro Civil tiene un costo fijo accesible.',
'Herencia y sucesión Chile: Guía de trámites legales',
'Guía paso a paso para tramitar herencia y posesión efectiva en Chile. Documentos y requisitos.',
ARRAY['herencia', 'posesión efectiva', 'trámites legales', 'sucesión'],
'Guías',
'/assets/images/blog/guias.jpg',
true,
(NOW() - INTERVAL '13 days')::timestamptz,
'Funeraria Santa Margarita'),

('Cómo elegir una funeraria de confianza en Chile',
'como-elegir-funeraria-confianza-chile',
'Criterios profesionales para elegir una funeraria confiable: transparencia, servicios, precios y atención 24/7.',
E'Elegir una funeraria es una decisión que generalmente debe tomarse en un momento de vulnerabilidad emocional. Conocer los **criterios clave** con anticipación le permitirá decidir informadamente.\n\n## Criterios fundamentales\n\n### 1. Transparencia en precios\n\n- Publicar precios de forma clara\n- No cobrar servicios ocultos\n- Ofrecer planes con cobertura detallada\n- Cumplir normativa SERNAC\n\n### 2. Disponibilidad 24/7\n\nEl fallecimiento no avisa. Una funeraria profesional debe estar disponible siempre.\n\n### 3. Experiencia y trayectoria\n\n- Años de operación\n- Testimonios de familias atendidas\n- Reputación en la comunidad\n\n### 4. Gama de servicios\n\n- Planes desde esenciales hasta premium\n- Opciones de cremación y sepultura\n- Servicios de memorial y obituario\n- Gestión de trámites legales\n\n### 5. Trato humano\n\n- Cómo le atienden en la primera llamada\n- Si muestran empatía genuina\n- Si respetan sus creencias y deseos\n\n---\n\n**En Funeraria Santa Margarita cumplimos con todos estos criterios.** Planes desde **$1.290.000** con atención 24/7. [Conozca nuestra propuesta →](/planes) o [contáctenos →](/contacto).\n\n---\n\n## Señales de alerta\n\nDesconfíe de una funeraria que:\n\n- **No publique precios**\n- **Presione** para decisiones inmediatas\n- **No permita** comparar opciones\n- **Cobre anticipos** sin contrato claro\n\n## Preguntas Frecuentes\n\n### ¿Puedo cambiar de funeraria después de contratar?\nDepende del contrato. Ofrecemos condiciones claras y flexibles.\n\n### ¿Qué debo preguntar en la primera llamada?\nPlanes disponibles, qué incluye cada uno, formas de pago, disponibilidad y gestión de trámites.',
'Cómo elegir funeraria de confianza en Chile',
'Criterios para elegir una funeraria confiable: transparencia, disponibilidad 24/7 y trato humano.',
ARRAY['elegir funeraria', 'funeraria confiable', 'Chile', 'transparencia'],
'Guías',
'/assets/images/blog/guias.jpg',
true,
(NOW() - INTERVAL '16 days')::timestamptz,
'Funeraria Santa Margarita'),

('Memoriales digitales: La nueva forma de honrar a quienes amamos',
'memoriales-digitales-nueva-forma-honrar',
'Descubra los memoriales digitales: un espacio permanente en línea para recordar y homenajear a su ser querido.',
E'La tecnología ha abierto nuevas posibilidades para mantener vivo el recuerdo. Los **memoriales digitales** son una de las innovaciones más significativas.\n\n## ¿Qué es un memorial digital?\n\nEs un espacio en línea dedicado a honrar la memoria de una persona fallecida:\n\n- **Accesible** desde cualquier lugar del mundo\n- **Permite interacción**: condolencias de familiares y amigos\n- **Preserva la historia**: fotografías, biografía y tributos permanentes\n- **Es compartible**: enlace para personas que no pudieron asistir\n\n## Características de nuestros memoriales\n\n### Perfil personalizado\n\n- Fotografía del ser querido\n- Fechas de nacimiento y fallecimiento\n- Biografía personalizada\n- Ciudad de residencia\n\n### Espacio de condolencias\n\nFamiliares y amigos dejan mensajes creando un libro de condolencias digital permanente.\n\n### Ofrendas virtuales\n\n- Coronas de flores digitales\n- Velas virtuales\n- Mensajes especiales\n\n---\n\n**Cree un memorial permanente.** Visite nuestra sección de [Memoriales →](/memoriales) y descubra cómo preservar su legado. [Contáctenos →](/contacto) para crear uno personalizado.\n\n---\n\n## ¿Por qué elegir un memorial digital?\n\n### Para familias dispersas\n\nCuando los familiares viven en distintas ciudades o países, es un **punto de encuentro virtual**.\n\n### Para las nuevas generaciones\n\nNietos y bisnietos podrán conocer la historia de sus ancestros.\n\n### Complemento al cementerio\n\nNo reemplaza la visita, sino que la **complementa** con accesibilidad 24 horas.\n\n## Preguntas Frecuentes\n\n### ¿Cuánto tiempo se mantiene activo?\nNuestros memoriales son permanentes, sin costo adicional.\n\n### ¿Puedo agregar fotos después?\nSí. Los memoriales pueden actualizarse a través de nuestro equipo.',
'Memoriales digitales: Honrar la memoria en línea',
'Memoriales digitales permanentes. Espacio en línea para recordar, homenajear y compartir.',
ARRAY['memorial digital', 'innovación funeraria', 'tecnología', 'recuerdo'],
'Novedades',
'/assets/images/blog/novedades.jpg',
true,
(NOW() - INTERVAL '1 day')::timestamptz,
'Funeraria Santa Margarita'),

('Tendencias funerarias 2025: Hacia servicios más humanos',
'tendencias-funerarias-2025-servicios-humanos',
'Las tendencias funerarias en Chile apuntan hacia ceremonias más personalizadas, ecológicas y tecnológicas.',
E'La industria funeraria en Chile está viviendo una transformación profunda. Las familias buscan servicios que reflejen la **identidad única** de cada persona.\n\n## Principales tendencias para 2025\n\n### 1. Personalización total\n\n- Música seleccionada por la familia\n- Decoración temática\n- Videos tributo con momentos especiales\n- Lecturas personalizadas\n\n### 2. Ceremonias ecológicas\n\n- Urnas biodegradables\n- Bosques de cenizas\n- Ataúdes de materiales sustentables\n\n### 3. Tecnología al servicio del recuerdo\n\n- **Memoriales digitales** con condolencias en línea\n- **Streaming** de ceremonias\n- **Códigos QR** en lápidas con contenido multimedia\n\n### 4. Previsión funeraria como tendencia\n\n- Mayor conciencia sobre costos funerarios\n- Deseo de no dejar cargas a la familia\n- Planes accesibles con precios congelados\n\n---\n\n**En Funeraria Santa Margarita ya implementamos estas tendencias.** Desde memoriales digitales hasta ceremonias 100% personalizadas. [Conozca nuestros servicios →](/planes) o llame al **+56 9 6433 3760**.\n\n---\n\n### 5. Transparencia y derechos del consumidor\n\nEl SERNAC exige:\n\n- Publicación clara de precios\n- Prohibición de ventas bajo presión\n- Derecho a cotizar en múltiples funerarias\n- Contratos claros y sin letra chica\n\n## Preguntas Frecuentes\n\n### ¿Puedo solicitar una ceremonia ecológica?\nSí. Contamos con opciones de urnas biodegradables.\n\n### ¿Ofrecen streaming de ceremonias?\nSí. Para familias con miembros en otras ciudades o países.',
'Tendencias funerarias 2025: Servicios más humanos',
'Tendencias funerarias 2025 en Chile: personalización, ecología, tecnología y transparencia.',
ARRAY['tendencias funerarias', '2025', 'innovación', 'personalización'],
'Novedades',
'/assets/images/blog/novedades.jpg',
true,
(NOW() - INTERVAL '2 days')::timestamptz,
'Funeraria Santa Margarita');
